### ISSUE TITLE
Unable to read MAT-file Not a binary MAT-file. Try load -ASCII to read as text

### ISSUE THREAD

**Issue by MaxKinny** [lokesh1agarwal/SDI#1]
When I load the mat file in my computer, it returned the error as follow:
```
Unable to read MAT-file Not a binary MAT-file. Try load -ASCII to read as text.
```
I both try on a win10 R2015a and Ubuntu16.04 R2017R environment but received the same problem. How can I solve this problem?

**Comment by lokesh-kedia** [comment]
It is opening in the browser itself, but if u want to open it on your system then u an try notepad++ or matlab.
If u tried matlab and getting same error then u may write load -ASCII in matlab terminal and then load mat file or run program.
